---
title: "Genera dataset"
author: "Jordi"
date: "8/3/2020"
output: html_document
---

```{r}
library(spatstat)

set.seed(123)
```


## Classifier according to known function

```{r}
class = function (x, y) {
    # 3x^2 - 4xy +4y = 2
    return (3*x^2 - 4*x*y +4*y < 2)
}

col.class = function(x, y) {
  if (class(x,y)) return(1)
  else return(0)
}
```

## Generating uniform points

```{r}
set.seed(1234)
color = c("blue", "green2")
error = FALSE
 # 100 random points in the unit square
N = 100
pp <- runifpoint(N)

for (i in c(1:N)) {
  pp$class[i] = col.class(pp$x[i], pp$y[i]) # assign the class
}
# adding optional error
if (error) {
  pp$x = pp$x + rnorm(N, 0, 1/10)
  pp$y = pp$y + rnorm(N, 0, 1/10)
}

plot(pp$x, pp$y, asp = 1, col = pp$class+1)
```

### Finishing

```{r}
# generate a dataframe from the points in pp and the class
df = data.frame(x = pp$x, y = pp$y, Class = pp$class)
# convert to .csv
write.csv(df, "simpledata.csv", row.names = FALSE)
```

# Data for regresion
Revealed truth:
```{r}
f = function(x, y) {
  return(sin(x) + 1/4*x -1/3*y^2 + 2)
}
```

```{r}
N = 500
pp.reg = runifpoint(N, win=owin(c(0,5),c(-4,4)))
pp.reg$t = f(pp.reg$x, pp.reg$y) + rnorm(N, 0, 1/10)
```

```{r}
# generate a dataframe from the points in pp and the class
df.reg = data.frame(x1 = pp.reg$x, x2 = pp.reg$y, y = pp.reg$t)
# convert to .csv
write.csv(df.reg, "reg_data.csv", row.names = FALSE)
```




